### ISSUE TITLE
Input will not accept a variable.

### ISSUE THREAD

**Issue by leebaird** [iSECPartners/sslyze#101]
I'm using a bash wrapper to automate sslyze. 
$location is the variable of my input list. Example: /root/list

sslyze --targets_in=$location --resum --certinfo=basic --compression --reneg --sslv2 --sslv3 —hide_rejected_ciphers

**Comment by tomrittervg** [comment]
Hi, thanks for your interest!  The current development repository for this repo is at https://github.com/nabla-c0d3/sslyze , please raise any issues there.
