### ISSUE TITLE
sslyze doesn't work on mac os 

### ISSUE THREAD

**Issue by tsmall888** [iSECPartners/sslyze#103]
Hi!

I has been installed sslyze using homebrew on mac os. For ALL target hosts I see following output:
```
[..]
CHECKING HOST(S) AVAILABILITY
 -----------------------------

   google.com:443                      => 127.0.0.1:443
[..]
```
and "Socket error" exception next.

As you can see destination ip is 127.0.0.1, but google.com correctly resolved from me.
Can you check this?

Thanks!

**Comment by tomrittervg** [comment]
Thanks for your report; please refile it at https://github.com/nabla-c0d3/sslyze where sslyze development now occurs.  Thanks!
